apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service-deployment
  namespace: hone-namespace
spec:
  replicas: 1
  # 아래의 label은 replicaset이 관리해야 할 파드를 결정하는데 사용
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      # 아래의 labels는 service의 selector.app과 일치해야함
      labels:
        app: ai-service
    spec:
      nodeSelector:
          gpu-memory-size: high
      containers:
      - name: ai-service
        image: 565393066924.dkr.ecr.ap-northeast-2.amazonaws.com/hone-namespace/ai-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: hone-secrets
              key: S3_BUCKET
        - name: ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: hone-secrets
              key: ACCESS_KEY
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: hone-secrets
              key: SECRET_KEY
        - name: HUGGINGFACE_TOKEN
          valueFrom:
            secretKeyRef:
              name: hone-secrets
              key: HUGGINGFACE_TOKEN
        # 컨테이너 상태 확인을 통해 롤링업데이트 최적화 
        readinessProbe:
          httpGet:
            # healthcheck 경로
            path: /actuator/health
            port: 8080
          # 컨테이너 시작 후 지연
          initialDelaySeconds: 10
          # 확인 반복 주기
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ai-service-service
  namespace: hone-namespace
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: ai-service