apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: member-service
  template:
    metadata:
      labels:
        app: member-service
    spec:
      containers:
      - name: member-service
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8080
        env:
        # TODO: member-service에 필요한 환경 변수들을 여기에 정의해야 합니다.
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: hone-secrets
              key: DB_HOST
        - name: DB_ID
          valueFrom:
            secretKeyRef:
              name: hone-secrets
              key: DB_ID
        - name: DB_PW
          valueFrom:
            secretKeyRef:
              name: hone-secrets
              key: DB_PW
        - name: MAIL_PORT
          valueFrom:
            secretKeyRef:
              name: hone-secrets
              key: MAIL_PORT
        - name: MAIL_ID
          valueFrom:
            secretKeyRef:
              name: hone-secrets
              key: MAIL_ID
        - name: MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hone-secrets
              key: MAIL_PASSWORD
        - name: BUSINESS_NUMBER
          valueFrom:
            secretKeyRef:
              name: hone-secrets
              key: BUSINESS_NUMBER
        - name: SECRET_KEY_AT
          valueFrom:
            secretKeyRef:
              name: hone-secrets
              key: SECRET_KEY_AT
        - name: SECRET_KEY_RT
          valueFrom:
            secretKeyRef:
              name: hone-secrets
              key: SECRET_KEY_RT

        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 15
          timeoutSeconds: 10

        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 15
          timeoutSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: member-service
  namespace: hone-namespace
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: member-service
