apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service-deployment
  namespace: hone-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: hone-nodes
      containers:
      - name: search-service
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8080
        env:
        # TODO: search-service에 필요한 환경 변수들을 여기에 정의해야 합니다.
        # - name: ELASTIC_HOST
        #   valueFrom:
        #     secretKeyRef:
        #       name: hone-secrets
        #       key: ELASTIC_HOST
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: hone-secrets
              key: DB_HOST
        - name: DB_ID
          valueFrom:
            secretKeyRef:
              name: hone-secrets
              key: DB_ID
        - name: DB_PW
          valueFrom:
            secretKeyRef:
              name: hone-secrets
              key: DB_PW

        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 15

        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 15

---
apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: hone-namespace
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: search-service
